name = "portfolio"
compatibility_date = "2024-12-15"
pages_build_output_dir = "./dist"

compatibility_flags = [
  "nodejs_compat",
  "disable_nodejs_process_v2"
]

[[kv_namespaces]]
binding = "App"
id = "14f671e9bfab4ca9af8a49dfa48bef4e"